/* eslint-disable */
// Code generated by web/scripts/generate-api.mjs from docs/swagger.json. DO NOT EDIT.

export interface ApiEnvelope<T = unknown> {
  code: number
  data?: T
  message?: string
}

export interface Schemas {
  'db.TrafficRecord': DbTrafficRecord
  'dto.ApplyClientUpdateRequest': DtoApplyClientUpdateRequest
  'dto.ApplyServerUpdateRequest': DtoApplyServerUpdateRequest
  'dto.CheckUpdateResponse': DtoCheckUpdateResponse
  'dto.ClientListItem': DtoClientListItem
  'dto.ClientResponse': DtoClientResponse
  'dto.ConfigUpdateResponse': DtoConfigUpdateResponse
  'dto.CreateClientRequest': DtoCreateClientRequest
  'dto.ExecuteShellRequest': DtoExecuteShellRequest
  'dto.HourlyTrafficResponse': DtoHourlyTrafficResponse
  'dto.LoginRequest': DtoLoginRequest
  'dto.LoginResponse': DtoLoginResponse
  'dto.ProxyRule': DtoProxyRule
  'dto.ScreenshotResponse': DtoScreenshotResponse
  'dto.ServerConfigInfo': DtoServerConfigInfo
  'dto.ServerConfigPart': DtoServerConfigPart
  'dto.ServerConfigResponse': DtoServerConfigResponse
  'dto.ServerStatus': DtoServerStatus
  'dto.ShellExecuteResponse': DtoShellExecuteResponse
  'dto.StatusResponse': DtoStatusResponse
  'dto.SystemStatsResponse': DtoSystemStatsResponse
  'dto.TokenCheckResponse': DtoTokenCheckResponse
  'dto.TrafficStatsResponse': DtoTrafficStatsResponse
  'dto.TrafficTotals': DtoTrafficTotals
  'dto.UpdateClientRequest': DtoUpdateClientRequest
  'dto.UpdateServerConfigRequest': DtoUpdateServerConfigRequest
  'dto.VersionInfo': DtoVersionInfo
  'dto.WebConfigInfo': DtoWebConfigInfo
  'dto.WebConfigPart': DtoWebConfigPart
  'handler.InstallCommandResponse': HandlerInstallCommandResponse
  'handler.Response': HandlerResponse
}

export interface DbTrafficRecord {
  inbound?: number
  outbound?: number
  timestamp?: number
}

export interface DtoApplyClientUpdateRequest {
  client_id: string
  download_url: string
}

export interface DtoApplyServerUpdateRequest {
  download_url: string
  restart?: boolean
}

export interface DtoCheckUpdateResponse {
  asset_name?: string
  asset_size?: number
  available?: boolean
  current?: string
  download_url?: string
  latest?: string
  release_note?: string
}

export interface DtoClientListItem {
  arch?: string
  id?: string
  last_offline_at?: number
  last_ping?: string
  nickname?: string
  online?: boolean
  os?: string
  remote_addr?: string
  rule_count?: number
  version?: string
}

export interface DtoClientResponse {
  arch?: string
  id?: string
  last_offline_at?: number
  last_ping?: string
  nickname?: string
  online?: boolean
  os?: string
  remote_addr?: string
  rules?: Array<DtoProxyRule>
  version?: string
}

export interface DtoConfigUpdateResponse {
  applied_runtime_fields?: Array<string>
  restart_required_fields?: Array<string>
  status?: string
}

export interface DtoCreateClientRequest {
  id: string
  rules?: Array<DtoProxyRule>
}

export interface DtoExecuteShellRequest {
  command: string
  timeout?: number
}

export interface DtoHourlyTrafficResponse {
  records?: Array<DbTrafficRecord>
}

export interface DtoLoginRequest {
  password: string
  username: string
}

export interface DtoLoginResponse {
  token?: string
}

export interface DtoProxyRule {
  auth_enabled?: boolean
  auth_password?: string
  auth_username?: string
  enabled?: boolean
  local_ip?: string
  local_port?: number
  name?: string
  port_status?: string
  remote_port?: number
  type?: string
}

export interface DtoScreenshotResponse {
  data?: string
  error?: string
  height?: number
  timestamp?: number
  width?: number
}

export interface DtoServerConfigInfo {
  bind_addr?: string
  bind_port?: number
  client_response_timeout_sec?: number
  heartbeat_sec?: number
  heartbeat_timeout?: number
  max_client_proxies?: number
  token?: string
}

export interface DtoServerConfigPart {
  bind_addr?: string
  bind_port?: number
  client_response_timeout_sec?: number
  heartbeat_sec?: number
  heartbeat_timeout?: number
  max_client_proxies?: number
  token?: string
}

export interface DtoServerConfigResponse {
  server?: DtoServerConfigInfo
  web?: DtoWebConfigInfo
}

export interface DtoServerStatus {
  bind_addr?: string
  bind_port?: number
}

export interface DtoShellExecuteResponse {
  error?: string
  exit_code?: number
  output?: string
}

export interface DtoStatusResponse {
  client_count?: number
  server?: DtoServerStatus
}

export interface DtoSystemStatsResponse {
  cpu_usage?: number
  disk_total?: number
  disk_usage?: number
  disk_used?: number
  memory_total?: number
  memory_usage?: number
  memory_used?: number
}

export interface DtoTokenCheckResponse {
  username?: string
  valid?: boolean
}

export interface DtoTrafficStatsResponse {
  traffic_24h?: DtoTrafficTotals
  traffic_total?: DtoTrafficTotals
}

export interface DtoTrafficTotals {
  inbound?: number
  outbound?: number
}

export interface DtoUpdateClientRequest {
  nickname?: string
  rules?: Array<DtoProxyRule>
}

export interface DtoUpdateServerConfigRequest {
  server?: DtoServerConfigPart
  web?: DtoWebConfigPart
}

export interface DtoVersionInfo {
  arch?: string
  build_time?: string
  git_commit?: string
  go_version?: string
  os?: string
  version?: string
}

export interface DtoWebConfigInfo {
  bind_port?: number
  enabled?: boolean
  password?: string
  username?: string
}

export interface DtoWebConfigPart {
  bind_port?: number
  enabled?: boolean
  password?: string
  username?: string
}

export interface HandlerInstallCommandResponse {
  expires_at?: number
  token?: string
  tunnel_port?: number
}

export interface HandlerResponse {
  code?: number
  data?: unknown
  message?: string
}

export interface Operations {
  'GET /api/auth/check': {
    response: HandlerResponse & { data?: DtoTokenCheckResponse }
    result: DtoTokenCheckResponse
  }
  'POST /api/auth/login': {
    requestBody: DtoLoginRequest
    response: HandlerResponse & { data?: DtoLoginResponse }
    result: DtoLoginResponse
  }
  'DELETE /api/client/{id}': {
    pathParams: { id: string }
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'GET /api/client/{id}': {
    pathParams: { id: string }
    response: HandlerResponse & { data?: DtoClientResponse }
    result: DtoClientResponse
  }
  'PUT /api/client/{id}': {
    pathParams: { id: string }
    requestBody: DtoUpdateClientRequest
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'POST /api/client/{id}/disconnect': {
    pathParams: { id: string }
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'GET /api/client/{id}/logs': {
    pathParams: { id: string }
    queryParams: { follow?: boolean; level?: string; lines?: number }
    response: string
    result: string
  }
  'POST /api/client/{id}/push': {
    pathParams: { id: string }
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'POST /api/client/{id}/restart': {
    pathParams: { id: string }
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'GET /api/client/{id}/screenshot': {
    pathParams: { id: string }
    queryParams: { quality?: number }
    response: HandlerResponse & { data?: DtoScreenshotResponse }
    result: DtoScreenshotResponse
  }
  'POST /api/client/{id}/shell': {
    pathParams: { id: string }
    requestBody: DtoExecuteShellRequest
    response: HandlerResponse & { data?: DtoShellExecuteResponse }
    result: DtoShellExecuteResponse
  }
  'GET /api/client/{id}/system-stats': {
    pathParams: { id: string }
    response: HandlerResponse & { data?: DtoSystemStatsResponse }
    result: DtoSystemStatsResponse
  }
  'GET /api/clients': {
    response: HandlerResponse & { data?: Array<DtoClientListItem> }
    result: Array<DtoClientListItem>
  }
  'POST /api/clients': {
    requestBody: DtoCreateClientRequest
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'GET /api/config': {
    response: HandlerResponse & { data?: DtoServerConfigResponse }
    result: DtoServerConfigResponse
  }
  'PUT /api/config': {
    requestBody: DtoUpdateServerConfigRequest
    response: HandlerResponse & { data?: DtoConfigUpdateResponse }
    result: DtoConfigUpdateResponse
  }
  'POST /api/install/generate': {
    response: HandlerInstallCommandResponse
    result: HandlerInstallCommandResponse
  }
  'GET /api/status': {
    response: HandlerResponse & { data?: DtoStatusResponse }
    result: DtoStatusResponse
  }
  'GET /api/traffic/hourly': {
    queryParams: { hours?: number }
    response: HandlerResponse & { data?: DtoHourlyTrafficResponse }
    result: DtoHourlyTrafficResponse
  }
  'GET /api/traffic/stats': {
    response: HandlerResponse & { data?: DtoTrafficStatsResponse }
    result: DtoTrafficStatsResponse
  }
  'POST /api/update/apply/client': {
    requestBody: DtoApplyClientUpdateRequest
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'POST /api/update/apply/server': {
    requestBody: DtoApplyServerUpdateRequest
    response: HandlerResponse
    result: ApiEnvelope<unknown>
  }
  'GET /api/update/check/client': {
    queryParams: { arch?: string; os?: string }
    response: HandlerResponse & { data?: DtoCheckUpdateResponse }
    result: DtoCheckUpdateResponse
  }
  'GET /api/update/check/server': {
    response: HandlerResponse & { data?: DtoCheckUpdateResponse }
    result: DtoCheckUpdateResponse
  }
  'GET /api/update/version': {
    response: HandlerResponse & { data?: DtoVersionInfo }
    result: DtoVersionInfo
  }
}

export type OperationResult<K extends keyof Operations> = Operations[K]['result']
export type OperationResponse<K extends keyof Operations> = Operations[K]['response']
export type OperationPathParams<K extends keyof Operations> = Operations[K] extends { pathParams: infer T } ? T : never
export type OperationQuery<K extends keyof Operations> = Operations[K] extends { queryParams: infer T } ? T : never
export type OperationRequestBody<K extends keyof Operations> = Operations[K] extends { requestBody: infer T } ? T : never

