import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const webDir = path.resolve(scriptDir, '..')
const rootDir = path.resolve(webDir, '..')
const swaggerPath = path.join(rootDir, 'docs', 'swagger.json')
const outputPath = path.join(webDir, 'src', 'api', 'generated.ts')
const swagger = JSON.parse(fs.readFileSync(swaggerPath, 'utf8'))
const definitions = swagger.definitions ?? {}
const definitionEntries = Object.entries(definitions).sort(([left], [right]) => left.localeCompare(right))

const aliasCounts = new Map()
const typeNames = new Map()
for (const [name] of definitionEntries) {
  const alias = uniqueTypeName(toPascalCase(name))
  typeNames.set(name, alias)
}

const lines = [
  '/* eslint-disable */',
  '// Code generated by web/scripts/generate-api.mjs from docs/swagger.json. DO NOT EDIT.',
  '',
  'export interface ApiEnvelope<T = unknown> {',
  '  code: number',
  '  data?: T',
  '  message?: string',
  '}',
  '',
]

if (definitionEntries.length > 0) {
  lines.push('export interface Schemas {')
  for (const [name] of definitionEntries) {
    lines.push(`  '${name}': ${typeNames.get(name)}`)
  }
  lines.push('}')
  lines.push('')
}

for (const [name, schema] of definitionEntries) {
  lines.push(renderNamedType(typeNames.get(name), schema))
  lines.push('')
}

lines.push('export interface Operations {')
for (const operation of collectOperations(swagger.paths ?? {})) {
  lines.push(`  '${operation.key}': {`)
  if (operation.pathParams) {
    lines.push(`    pathParams: ${operation.pathParams}`)
  }
  if (operation.queryParams) {
    lines.push(`    queryParams: ${operation.queryParams}`)
  }
  if (operation.requestBody) {
    lines.push(`    requestBody: ${operation.requestBody}`)
  }
  lines.push(`    response: ${operation.response}`)
  lines.push(`    result: ${operation.result}`)
  lines.push('  }')
}
lines.push('}')
lines.push('')
lines.push(`export type OperationResult<K extends keyof Operations> = Operations[K]['result']`)
lines.push(`export type OperationResponse<K extends keyof Operations> = Operations[K]['response']`)
lines.push(`export type OperationPathParams<K extends keyof Operations> = Operations[K] extends { pathParams: infer T } ? T : never`)
lines.push(`export type OperationQuery<K extends keyof Operations> = Operations[K] extends { queryParams: infer T } ? T : never`)
lines.push(`export type OperationRequestBody<K extends keyof Operations> = Operations[K] extends { requestBody: infer T } ? T : never`)
lines.push('')

fs.writeFileSync(outputPath, `${lines.join('\n')}\n`)

function collectOperations(paths) {
  const operations = []
  for (const route of Object.keys(paths).sort((left, right) => left.localeCompare(right))) {
    const pathItem = paths[route]
    for (const method of Object.keys(pathItem).sort()) {
      const operation = pathItem[method]
      const key = `${method.toUpperCase()} ${route}`
      const successSchema = getSuccessSchema(operation.responses ?? {})
      operations.push({
        key,
        pathParams: buildParamObject(operation.parameters ?? [], 'path'),
        queryParams: buildParamObject(operation.parameters ?? [], 'query'),
        requestBody: getRequestBodyType(operation.parameters ?? []),
        response: schemaToTs(successSchema),
        result: extractResultType(successSchema),
      })
    }
  }
  return operations
}

function renderNamedType(name, schema) {
  if (canRenderAsInterface(schema)) {
    return `export interface ${name} ${renderObjectBody(schema)}`
  }
  return `export type ${name} = ${schemaToTs(schema)}`
}

function canRenderAsInterface(schema) {
  return Boolean(schema) && !schema.$ref && !schema.allOf && (schema.type === 'object' || schema.properties || schema.additionalProperties)
}

function renderObjectBody(schema) {
  const properties = schema.properties ?? {}
  const required = new Set(schema.required ?? [])
  const entries = Object.keys(properties).sort((left, right) => left.localeCompare(right))
  const parts = ['{']
  for (const propertyName of entries) {
    const optional = required.has(propertyName) ? '' : '?'
    parts.push(`  ${quoteProperty(propertyName)}${optional}: ${schemaToTs(properties[propertyName])}`)
  }
  if (schema.additionalProperties) {
    parts.push(`  [key: string]: ${schemaToTs(schema.additionalProperties)}`)
  }
  if (parts.length === 1) {
    parts.push('  [key: string]: unknown')
  }
  parts.push('}')
  return parts.join('\n')
}

function schemaToTs(schema) {
  if (!schema) {
    return 'unknown'
  }
  if (schema.$ref) {
    return resolveRef(schema.$ref)
  }
  if (schema.allOf) {
    return schema.allOf.map((item) => parenthesize(schemaToTs(item))).join(' & ')
  }
  if (schema.oneOf) {
    return schema.oneOf.map((item) => parenthesize(schemaToTs(item))).join(' | ')
  }
  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map((value) => JSON.stringify(value)).join(' | ')
  }
  if (schema.type === 'array') {
    return `Array<${schemaToTs(schema.items)}>`
  }
  if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    const parts = []
    const properties = schema.properties ?? {}
    const required = new Set(schema.required ?? [])
    const entries = Object.keys(properties).sort((left, right) => left.localeCompare(right))
    for (const propertyName of entries) {
      const optional = required.has(propertyName) ? '' : '?'
      parts.push(`${quoteProperty(propertyName)}${optional}: ${schemaToTs(properties[propertyName])}`)
    }
    if (schema.additionalProperties) {
      parts.push(`[key: string]: ${schemaToTs(schema.additionalProperties)}`)
    }
    if (parts.length === 0) {
      return 'Record<string, unknown>'
    }
    return `{ ${parts.join('; ')} }`
  }

  switch (schema.type) {
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'string':
      return 'string'
    default:
      return 'unknown'
  }
}

function extractResultType(schema) {
  if (!schema) {
    return 'void'
  }
  if (isEnvelopeRef(schema.$ref)) {
    return 'ApiEnvelope<unknown>'
  }
  if (schema.allOf) {
    const hasEnvelope = schema.allOf.some((item) => isEnvelopeRef(item.$ref))
    if (hasEnvelope) {
      for (const item of schema.allOf) {
        const dataSchema = item?.properties?.data
        if (dataSchema) {
          return schemaToTs(dataSchema)
        }
      }
      return 'ApiEnvelope<unknown>'
    }
  }
  if (schema.properties?.code && schema.properties?.data) {
    return schemaToTs(schema.properties.data)
  }
  return schemaToTs(schema)
}

function getSuccessSchema(responses) {
  const successCodes = Object.keys(responses)
    .filter((code) => code.startsWith('2'))
    .sort((left, right) => Number(left) - Number(right))
  const response = successCodes.length > 0 ? responses[successCodes[0]] : undefined
  return response?.schema
}

function buildParamObject(parameters, location) {
  const selected = parameters.filter((parameter) => parameter.in === location)
  if (selected.length === 0) {
    return null
  }

  const parts = selected
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((parameter) => {
      const optional = parameter.required ? '' : '?'
      return `${quoteProperty(parameter.name)}${optional}: ${parameterSchemaToTs(parameter)}`
    })

  return `{ ${parts.join('; ')} }`
}

function getRequestBodyType(parameters) {
  const bodyParameter = parameters.find((parameter) => parameter.in === 'body')
  if (!bodyParameter) {
    return null
  }
  return schemaToTs(bodyParameter.schema)
}

function parameterSchemaToTs(parameter) {
  if (parameter.schema) {
    return schemaToTs(parameter.schema)
  }
  if (parameter.type === 'array') {
    return `Array<${parameterSchemaToTs(parameter.items ?? {})}>`
  }
  switch (parameter.type) {
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'string':
      return 'string'
    default:
      return 'unknown'
  }
}

function resolveRef(ref) {
  const name = ref.replace('#/definitions/', '')
  return typeNames.get(name) ?? 'unknown'
}

function isEnvelopeRef(ref) {
  return typeof ref === 'string' && (ref === '#/definitions/handler.Response' || ref === '#/definitions/internal_server_router_handler.Response')
}

function parenthesize(typeName) {
  return typeName.includes(' & ') || typeName.includes(' | ') ? `(${typeName})` : typeName
}

function quoteProperty(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function toPascalCase(value) {
  const cleaned = value
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

  if (!cleaned) {
    return 'Schema'
  }
  return /^[0-9]/.test(cleaned) ? `Schema${cleaned}` : cleaned
}

function uniqueTypeName(baseName) {
  const count = aliasCounts.get(baseName) ?? 0
  aliasCounts.set(baseName, count + 1)
  return count === 0 ? baseName : `${baseName}${count + 1}`
}
