package handler

const shellInstallScript = `#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash install.sh -s <server:port> -t <token>

Options:
  -s  Tunnel server address, for example 10.0.0.2:7000
  -t  One-time install token generated by the server
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

github_api_get() {
  curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -H "User-Agent: GoTunnel-Installer" \
    "$1"
}

detect_os() {
  case "$(uname -s)" in
    Linux) echo "linux" ;;
    Darwin) echo "darwin" ;;
    *)
      echo "unsupported operating system: $(uname -s)" >&2
      exit 1
      ;;
  esac
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    i386|i686) echo "386" ;;
    armv7l|armv6l|arm) echo "arm" ;;
    *)
      echo "unsupported architecture: $(uname -m)" >&2
      exit 1
      ;;
  esac
}

SERVER_ADDR=""
INSTALL_TOKEN=""

while getopts ":s:t:h" opt; do
  case "$opt" in
    s) SERVER_ADDR="$OPTARG" ;;
    t) INSTALL_TOKEN="$OPTARG" ;;
    h)
      usage
      exit 0
      ;;
    :)
      echo "option -$OPTARG requires a value" >&2
      usage
      exit 1
      ;;
    \?)
      echo "unknown option: -$OPTARG" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$SERVER_ADDR" || -z "$INSTALL_TOKEN" ]]; then
  usage
  exit 1
fi

require_cmd curl
require_cmd tar
require_cmd mktemp

OS_NAME="$(detect_os)"
ARCH_NAME="$(detect_arch)"
INSTALL_ROOT="${HOME:-$(pwd)}/.gotunnel"
BIN_DIR="$INSTALL_ROOT/bin"
TARGET_BIN="$BIN_DIR/gotunnel-client"
LOG_FILE="$INSTALL_ROOT/client.log"
PID_FILE="$INSTALL_ROOT/client.pid"
TMP_DIR="$(mktemp -d)"
ARCHIVE_PATH="$TMP_DIR/gotunnel-client.tar.gz"
RELEASE_API_URL="https://api.github.com/repos/Flikify/Gotunnel/releases/latest"
ASSET_SUFFIX="-$OS_NAME-$ARCH_NAME.tar.gz"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

mkdir -p "$BIN_DIR"

RELEASE_JSON="$(github_api_get "$RELEASE_API_URL" | tr -d '\n')"
DOWNLOAD_URL="$(printf '%s' "$RELEASE_JSON" | grep -o "\"browser_download_url\":\"[^\"]*gotunnel-client-[^\"]*$ASSET_SUFFIX\"" | head -n 1 | cut -d '"' -f 4 | sed 's/\\u0026/&/g')"

if [[ -z "$DOWNLOAD_URL" ]]; then
  echo "failed to resolve GoTunnel client package for $OS_NAME/$ARCH_NAME from GitHub releases" >&2
  exit 1
fi

echo "Downloading GoTunnel client from $DOWNLOAD_URL"
curl -fsSL "$DOWNLOAD_URL" -o "$ARCHIVE_PATH"
tar -xzf "$ARCHIVE_PATH" -C "$TMP_DIR"

EXTRACTED_BIN="$(find "$TMP_DIR" -type f -name 'gotunnel-client*' ! -name '*.tar.gz' ! -name '*.zip' | head -n 1)"
if [[ -z "$EXTRACTED_BIN" ]]; then
  echo "failed to find extracted client binary" >&2
  exit 1
fi

cp "$EXTRACTED_BIN" "$TARGET_BIN"
chmod 0755 "$TARGET_BIN"

if [[ -f "$PID_FILE" ]]; then
  OLD_PID="$(cat "$PID_FILE" 2>/dev/null || true)"
  if [[ -n "$OLD_PID" ]]; then
    kill "$OLD_PID" >/dev/null 2>&1 || true
  fi
fi

nohup "$TARGET_BIN" -s "$SERVER_ADDR" -t "$INSTALL_TOKEN" >>"$LOG_FILE" 2>&1 &
NEW_PID=$!
echo "$NEW_PID" >"$PID_FILE"

echo "GoTunnel client installed to $TARGET_BIN"
echo "Client started in background with PID $NEW_PID"
echo "Logs: $LOG_FILE"
`

const powerShellInstallScript = `function Get-GoTunnelArch {
  switch ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()) {
    'x64' { return 'amd64' }
    'arm64' { return 'arm64' }
    'x86' { return '386' }
    default { throw "Unsupported architecture: $([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)" }
  }
}

function Get-GoTunnelDownloadUrl {
  param(
    [Parameter(Mandatory = $true)][string]$Arch
  )

  $Release = Invoke-RestMethod -Uri 'https://api.github.com/repos/Flikify/Gotunnel/releases/latest' -Headers @{
    'Accept' = 'application/vnd.github+json'
    'X-GitHub-Api-Version' = '2022-11-28'
    'User-Agent' = 'GoTunnel-Installer'
  }

  $Asset = $Release.assets |
    Where-Object { $_.name -match "^gotunnel-client-.*-windows-$Arch\.zip$" } |
    Select-Object -First 1

  if (-not $Asset) {
    throw "Failed to resolve GoTunnel client package for windows/$Arch from GitHub releases."
  }

  return $Asset.browser_download_url
}

function Install-GoTunnel {
  param(
    [Parameter(Mandatory = $true)][string]$Server,
    [Parameter(Mandatory = $true)][string]$Token
  )

  $Arch = Get-GoTunnelArch
  $InstallRoot = Join-Path $env:LOCALAPPDATA 'GoTunnel'
  $ExtractDir = Join-Path $InstallRoot 'extract'
  $ArchivePath = Join-Path $InstallRoot 'gotunnel-client.zip'
  $TargetPath = Join-Path $InstallRoot 'gotunnel-client.exe'
  $DownloadUrl = Get-GoTunnelDownloadUrl -Arch $Arch

  New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null

  Write-Host "Downloading GoTunnel client from $DownloadUrl"
  Invoke-WebRequest -Uri $DownloadUrl -OutFile $ArchivePath -MaximumRedirection 5

  if (Test-Path $ExtractDir) {
    Remove-Item -Path $ExtractDir -Recurse -Force
  }
  Expand-Archive -Path $ArchivePath -DestinationPath $ExtractDir -Force

  $Binary = Get-ChildItem -Path $ExtractDir -Recurse -File |
    Where-Object { $_.Name -eq 'gotunnel-client.exe' } |
    Select-Object -First 1

  if (-not $Binary) {
    throw 'Failed to find extracted client binary.'
  }

  Copy-Item -Path $Binary.FullName -Destination $TargetPath -Force

  Get-Process |
    Where-Object { $_.Path -eq $TargetPath } |
    Stop-Process -Force -ErrorAction SilentlyContinue

  Start-Process -FilePath $TargetPath -ArgumentList @('-s', $Server, '-t', $Token) -WindowStyle Hidden

  Write-Host "GoTunnel client installed to $TargetPath"
  Write-Host 'Client started in background.'
}
`
