#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash install.sh -s <server:port> -t <token>

Options:
  -s  Tunnel server address, for example 10.0.0.2:7000
  -t  One-time install token generated by the server
  -p  Optional CDN / GitHub proxy prefix, for example https://ghfast.top/
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

github_api_get() {
  curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -H "User-Agent: GoTunnel-Installer" \
    "$1"
}

detect_os() {
  case "$(uname -s)" in
    Linux) echo "linux" ;;
    Darwin) echo "darwin" ;;
    *)
      echo "unsupported operating system: $(uname -s)" >&2
      exit 1
      ;;
  esac
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    i386|i686) echo "386" ;;
    armv7l|armv6l|arm) echo "arm" ;;
    *)
      echo "unsupported architecture: $(uname -m)" >&2
      exit 1
      ;;
  esac
}

ensure_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    return
  fi

  if command -v sudo >/dev/null 2>&1; then
    echo "Re-running installer with sudo"
    if [[ -n "$CDN_PREFIX" ]]; then
      exec sudo bash "$0" -s "$SERVER_ADDR" -t "$INSTALL_TOKEN" -p "$CDN_PREFIX"
    fi
    exec sudo bash "$0" -s "$SERVER_ADDR" -t "$INSTALL_TOKEN"
  fi

  echo "installer must run as root (or with sudo)" >&2
  exit 1
}

apply_cdn_prefix() {
  local url="$1"
  if [[ -z "$CDN_PREFIX" ]]; then
    printf '%s' "$url"
    return
  fi
  printf '%s/%s' "${CDN_PREFIX%/}" "$url"
}

install_service() {
  local service_name="gotunnel-client"
  local service_args=(service install -s "$SERVER_ADDR" -t "$INSTALL_TOKEN" -data-dir "$DATA_DIR" -service-name "$service_name" -service-display-name "GoTunnel Client")

  if [[ "$OS_NAME" == "darwin" ]]; then
    service_name="com.gotunnel.client"
    service_args=(service install -s "$SERVER_ADDR" -t "$INSTALL_TOKEN" -data-dir "$DATA_DIR" -service-name "$service_name" -service-display-name "GoTunnel Client" -service-log-file "$LOG_DIR/client.log")
    mkdir -p "$LOG_DIR"
  fi

  "$TARGET_BIN" "${service_args[@]}"
}

SERVER_ADDR=""
INSTALL_TOKEN=""
CDN_PREFIX=""

while getopts ":s:t:p:h" opt; do
  case "$opt" in
    s) SERVER_ADDR="$OPTARG" ;;
    t) INSTALL_TOKEN="$OPTARG" ;;
    p) CDN_PREFIX="$OPTARG" ;;
    h)
      usage
      exit 0
      ;;
    :)
      echo "option -$OPTARG requires a value" >&2
      usage
      exit 1
      ;;
    \?)
      echo "unknown option: -$OPTARG" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$SERVER_ADDR" || -z "$INSTALL_TOKEN" ]]; then
  usage
  exit 1
fi

require_cmd curl
require_cmd tar
require_cmd mktemp

OS_NAME="$(detect_os)"
ARCH_NAME="$(detect_arch)"
ensure_root

if [[ "$OS_NAME" == "linux" ]]; then
  INSTALL_ROOT="/opt/gotunnel"
  DATA_DIR="/var/lib/gotunnel"
  LOG_DIR="/var/log/gotunnel"
else
  INSTALL_ROOT="/usr/local/lib/gotunnel"
  DATA_DIR="/Library/Application Support/GoTunnel"
  LOG_DIR="/Library/Logs/GoTunnel"
fi

BIN_DIR="$INSTALL_ROOT/bin"
TARGET_BIN="$BIN_DIR/gotunnel-client"
CONFIG_PATH="$DATA_DIR/client.yaml"
TMP_DIR="$(mktemp -d)"
ARCHIVE_PATH="$TMP_DIR/gotunnel-client.tar.gz"
RELEASE_API_URL="https://api.github.com/repos/Flikify/Gotunnel/releases/latest"
ASSET_SUFFIX="-$OS_NAME-$ARCH_NAME.tar.gz"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

mkdir -p "$BIN_DIR" "$DATA_DIR"

RELEASE_JSON="$(github_api_get "$RELEASE_API_URL" | tr -d '\n')"
DOWNLOAD_URL="$(printf '%s' "$RELEASE_JSON" | grep -o "\"browser_download_url\":\"[^\"]*gotunnel-client-[^\"]*$ASSET_SUFFIX\"" | head -n 1 | cut -d '"' -f 4 | sed 's/\\u0026/&/g')"

if [[ -z "$DOWNLOAD_URL" ]]; then
  echo "failed to resolve GoTunnel client package for $OS_NAME/$ARCH_NAME from GitHub releases" >&2
  exit 1
fi

DOWNLOAD_URL="$(apply_cdn_prefix "$DOWNLOAD_URL")"

echo "Downloading GoTunnel client from $DOWNLOAD_URL"
curl -fsSL "$DOWNLOAD_URL" -o "$ARCHIVE_PATH"
tar -xzf "$ARCHIVE_PATH" -C "$TMP_DIR"

EXTRACTED_BIN="$(find "$TMP_DIR" -type f -name 'gotunnel-client*' ! -name '*.tar.gz' ! -name '*.zip' | head -n 1)"
if [[ -z "$EXTRACTED_BIN" ]]; then
  echo "failed to find extracted client binary" >&2
  exit 1
fi

cp "$EXTRACTED_BIN" "$TARGET_BIN"
chmod 0755 "$TARGET_BIN"

install_service

echo "GoTunnel client installed to $TARGET_BIN"
echo "Config written to $CONFIG_PATH"
