#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash install.sh -s <server:port> -t <token>

Options:
  -s  Tunnel server address, for example 10.0.0.2:7000
  -t  One-time install token generated by the server
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

github_api_get() {
  curl -fsSL \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -H "User-Agent: GoTunnel-Installer" \
    "$1"
}

detect_os() {
  case "$(uname -s)" in
    Linux) echo "linux" ;;
    Darwin) echo "darwin" ;;
    *)
      echo "unsupported operating system: $(uname -s)" >&2
      exit 1
      ;;
  esac
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    i386|i686) echo "386" ;;
    armv7l|armv6l|arm) echo "arm" ;;
    *)
      echo "unsupported architecture: $(uname -m)" >&2
      exit 1
      ;;
  esac
}

yaml_quote() {
  local value="${1//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

ensure_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    return
  fi

  if command -v sudo >/dev/null 2>&1; then
    echo "Re-running installer with sudo"
    exec sudo bash "$0" -s "$SERVER_ADDR" -t "$INSTALL_TOKEN"
  fi

  echo "installer must run as root (or with sudo)" >&2
  exit 1
}

write_config_file() {
  mkdir -p "$(dirname "$CONFIG_PATH")"
  cat >"$CONFIG_PATH" <<EOF
server: $(yaml_quote "$SERVER_ADDR")
token: $(yaml_quote "$INSTALL_TOKEN")
data_dir: $(yaml_quote "$DATA_DIR")
reconnect_min_sec: 5
reconnect_max_sec: 30
EOF
  chmod 0600 "$CONFIG_PATH"
}

install_linux_service() {
  require_cmd systemctl

  local unit_path="/etc/systemd/system/gotunnel-client.service"
  cat >"$unit_path" <<EOF
[Unit]
Description=GoTunnel Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$TARGET_BIN -c $CONFIG_PATH
WorkingDirectory=$DATA_DIR
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  chmod 0644 "$unit_path"
  systemctl daemon-reload
  systemctl enable --now gotunnel-client.service

  echo "Service installed: gotunnel-client.service"
  echo "Startup type: enabled"
  echo "Restart policy: always"
  systemctl --no-pager --full status gotunnel-client.service | sed -n '1,8p' || true
}

install_macos_service() {
  require_cmd launchctl

  local plist_path="/Library/LaunchDaemons/com.gotunnel.client.plist"
  mkdir -p "$LOG_DIR"

  cat >"$plist_path" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.gotunnel.client</string>
  <key>ProgramArguments</key>
  <array>
    <string>$TARGET_BIN</string>
    <string>-c</string>
    <string>$CONFIG_PATH</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>$DATA_DIR</string>
  <key>StandardOutPath</key>
  <string>$LOG_DIR/client.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/client-error.log</string>
</dict>
</plist>
EOF

  chmod 0644 "$plist_path"
  launchctl bootout system "$plist_path" >/dev/null 2>&1 || true
  launchctl bootstrap system "$plist_path"
  launchctl enable system/com.gotunnel.client
  launchctl kickstart -k system/com.gotunnel.client

  echo "Service installed: com.gotunnel.client"
  echo "Startup type: RunAtLoad"
  echo "Restart policy: KeepAlive"
  launchctl print system/com.gotunnel.client | sed -n '1,12p' || true
}

SERVER_ADDR=""
INSTALL_TOKEN=""

while getopts ":s:t:h" opt; do
  case "$opt" in
    s) SERVER_ADDR="$OPTARG" ;;
    t) INSTALL_TOKEN="$OPTARG" ;;
    h)
      usage
      exit 0
      ;;
    :)
      echo "option -$OPTARG requires a value" >&2
      usage
      exit 1
      ;;
    \?)
      echo "unknown option: -$OPTARG" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$SERVER_ADDR" || -z "$INSTALL_TOKEN" ]]; then
  usage
  exit 1
fi

require_cmd curl
require_cmd tar
require_cmd mktemp

OS_NAME="$(detect_os)"
ARCH_NAME="$(detect_arch)"
ensure_root

if [[ "$OS_NAME" == "linux" ]]; then
  INSTALL_ROOT="/opt/gotunnel"
  DATA_DIR="/var/lib/gotunnel"
  LOG_DIR="/var/log/gotunnel"
else
  INSTALL_ROOT="/usr/local/lib/gotunnel"
  DATA_DIR="/Library/Application Support/GoTunnel"
  LOG_DIR="/Library/Logs/GoTunnel"
fi

BIN_DIR="$INSTALL_ROOT/bin"
TARGET_BIN="$BIN_DIR/gotunnel-client"
CONFIG_PATH="$DATA_DIR/client.yaml"
TMP_DIR="$(mktemp -d)"
ARCHIVE_PATH="$TMP_DIR/gotunnel-client.tar.gz"
RELEASE_API_URL="https://api.github.com/repos/Flikify/Gotunnel/releases/latest"
ASSET_SUFFIX="-$OS_NAME-$ARCH_NAME.tar.gz"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

mkdir -p "$BIN_DIR" "$DATA_DIR"

RELEASE_JSON="$(github_api_get "$RELEASE_API_URL" | tr -d '\n')"
DOWNLOAD_URL="$(printf '%s' "$RELEASE_JSON" | grep -o "\"browser_download_url\":\"[^\"]*gotunnel-client-[^\"]*$ASSET_SUFFIX\"" | head -n 1 | cut -d '"' -f 4 | sed 's/\\u0026/&/g')"

if [[ -z "$DOWNLOAD_URL" ]]; then
  echo "failed to resolve GoTunnel client package for $OS_NAME/$ARCH_NAME from GitHub releases" >&2
  exit 1
fi

echo "Downloading GoTunnel client from $DOWNLOAD_URL"
curl -fsSL "$DOWNLOAD_URL" -o "$ARCHIVE_PATH"
tar -xzf "$ARCHIVE_PATH" -C "$TMP_DIR"

EXTRACTED_BIN="$(find "$TMP_DIR" -type f -name 'gotunnel-client*' ! -name '*.tar.gz' ! -name '*.zip' | head -n 1)"
if [[ -z "$EXTRACTED_BIN" ]]; then
  echo "failed to find extracted client binary" >&2
  exit 1
fi

cp "$EXTRACTED_BIN" "$TARGET_BIN"
chmod 0755 "$TARGET_BIN"

write_config_file

case "$OS_NAME" in
  linux)
    install_linux_service
    ;;
  darwin)
    install_macos_service
    ;;
esac

echo "GoTunnel client installed to $TARGET_BIN"
echo "Config written to $CONFIG_PATH"
