name: build-go-binary

on:
  release:
    types: [published] # 更推荐

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4

      - name: Check go.mod exists
        run: |
          if [ ! -f go.mod ]; then
            echo "::error::go.mod not found! Run 'go mod init' in your repo root and commit it."
            exit 1
          fi

      - uses: wangyoucao577/go-release-action@v1.51 # 建议用较新版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.24.3
          binary_name: "secure-proxy"
          # 下面参数仅当 main.go 不在仓库根目录时使用
          # main_package_path: ./cmd/proxy
