name: build-go-binary

on:
  push:
    branches:
      - main  # 可根据需要修改为你要监听的分支

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: Check go.mod exists
        run: |
          if [ ! -f go.mod ]; then
            echo "::error::go.mod not found! Run 'go mod init' in your repo root and commit it."
            exit 1
          fi

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          EXT=""
          if [ "${GOOS}" = "windows" ]; then EXT=".exe"; fi
          OUTPUT="build/gotunnel-${GOOS}-${GOARCH}${EXT}"
          go build -ldflags "-s -w" -o "$OUTPUT" .

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: gotunnel-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/gotunnel-${{ matrix.goos }}-${{ matrix.goarch }}*
