/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlassModal: typeof import('./src/components/GlassModal.vue')['default']
    GlassSwitch: typeof import('./src/components/GlassSwitch.vue')['default']
    GlassTag: typeof import('./src/components/GlassTag.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InlineLogPanel: typeof import('./src/components/InlineLogPanel.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
